### PR TITLE
Feature/add tests

### PR DESCRIPTION
**Pull request by ekate**
Adds framework to run E2E tests

### CODE REVIEW

**Comment by ekate** [comment]
@dismorfo , @andrewbattista  I asked you to review this. Could you please check that you can run tests using the instructions [here](https://github.com/nyudlts/ultraviolet-deposit/tree/feature/add_tests)

**Comment by dismorfo** [comment]
I should be done by today.

**Comment by dismorfo** [comment]
2 failed, 2 passed, 40 warnings in 370.58s (0:06:10) in my end.

`
========================================== short test summary info ===========================================
FAILED tests/test_ultraviolet_deposit.py::test_view - pywebpack.manifests.UnfinishedManifestError: {'status...
FAILED tests/e2e/test_deposit_e2e.py::test_upload_form[Chrome] - AssertionError: assert 'New upload' == 'In..
`

Looks like the test might be running before webpack is done.

**Comment by ekate** [comment]
@dismorfo Could you check if somewhere in the out it complains about templates path ?

**Comment by dismorfo** [comment]
In `def test_upload_form(running_app, live_server, browser)` I get 'Internal Server Error'

See: tests/e2e/test_deposit_e2e.py:27: AssertionError

Yes, I see an error related to templates:

`ERROR in ./js/invenio_theme/templates.js
Module not found: Error: Can't resolve '@templates' in '/var/folders/p9/bb75s7pj1yn3wj4zb21t4zp80000gn/T/tmpngowltmg/assets/js/invenio_theme'`

**Comment by ekate** [comment]
@dismorfo I removed webpack build  from configtest and modified the instructions, it's better to run it separately  to avoid collisions. Please try to run now using the new instructions. Before running delete the environment by running `pipenv --rm`.

**Comment by ekate** [comment]
@dismorfo , @andrewbattista based on the checks we made I've added requirements checks which run before test. Please try to install and run now

**Comment by dismorfo** [comment]
I got a "RuntimeError: Process exited with code 2" after I `$ git pull` the latest changes and ran the command `$ pipenv run invenio webpack buildall`.

See: https://gist.github.com/dismorfo/bdcc52e2f88e77ce97993f370fb68d98

**Comment by ekate** [comment]
@dismorfo according to your gist there was one step skipped in the setup
pipenv run pip install -e .
That one register module's own entry points, so if it is missing there is a  build error. I was able to reproduce it.
 Could you run the command above and then 
`pipenv run invenio webpack buildall`

**Comment by dismorfo** [comment]
Ok. I will try again.

**Comment by dismorfo** [comment]
Test failed. I'm looking into the out put now.

See: https://gist.github.com/dismorfo/93fdd1eb234d3550417ae0cb9db58d8c

**Comment by ekate** [comment]
As first 3 ones passed application setup was fine and client was able to connect to it. The ones which are failing are E2E. I can not say anything from gist. What o you see in the screenshort ?

**Comment by dismorfo** [comment]
Just a white screen from the test in the .e2e_screenshots

**Comment by ekate** [comment]
From the gist it looks like Chromedriver is able to connect to the browser and there are no javascript errors ( warnings are fine). I am not getting any errors so it is something environment dependent. I am thinking probably it is a load delay issue due to lack of resources ? To exclude it  I've added a 5 minutes sleep to the first E2E test. Could you please pull it and just run
 `pipenv run ./run-tests.sh`

**Comment by ekate** [comment]
@dismorfo as we discussed, I've added vagrant setup and confirmed that tests are passing on vagrant box (guest machine Centos 7). I used 2 different machines as hosts and it worked on both.  You can build the box from source or I can give you a box I already build

**Review by andrewbattista — APPROVED** [review]
This looks great! Thank you so much @ekate and @dismorfo for days and days of work on this. Glad we have a working framework for testing the deposit module

**Pull request merged**
